### ISSUE TITLE
"fire_db_2010: no such file or directory" during build

### ISSUE THREAD

**Issue by MikeTheCanuck** [BrianHGrant/emergency-response#3]
During the build of the vagrant box, I noticed a small error that looked like something that might cause unexpected failures once people start coding against this box.

Reproduction steps:
- clone the repo
- switch to dockerized-api branch (git checkout dockerized-api)
- ran vagrant up

Here's the error message I saw:

`==> default: bash: /home/vagrant/proj/data/fire_db_2010: No such file or directory`

Here's a bunch of the surrounding logged output around the red error - in case it isn't obvious which operation caused this error:

```
==> default: Running scripts as user vagrant...
==> default: Installing miniconda...
==> default: Python 3.5.2 :: Continuum Analytics, Inc.
==> default: Installing Jupyter...
==> default: Installing cvdjango...
==> default: Installing djangorestframework...
==> default: Creating DB Users...
==> default: CREATE ROLE
==> default: Loading DB...
==> default: CREATE DATABASE
==> default: bash: /home/vagrant/proj/data/fire_db_2010: No such file or directory
==> default: Configuring DB users...
==> default: GRANT
==> default: Setting postgres admin login to password authentication with password "vagrant"...
==> default:  * Restarting PostgreSQL 9.5 database server
==> default:    ...done.
==> default: ALTER ROLE
==> default:  * Restarting PostgreSQL 9.5 database server
==> default:    ...done.
==> default: Finished installing packages.
==> default: Run the following line on your host machine:
==> default: $ vagrant plugin install vagrant-vbguest
==> default: Running provisioner: docker...
```

**Comment by MikeTheCanuck** [comment]
Found the reference to fire_db_2010 on line 70 of provision_script.sh:
`
su postgres -c "psql fire < $PROJ/data/fire_db_2010"
`

**Comment by BrianHGrant** [comment]
Closing issue as box has been updated
